version: "3.5"

services:
  postgres-server:
    image: postgres:10.5
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sci_search
      - POSTGRES_USER=forensx
      - POSTGRES_PASSWORD=forensx
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d/"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=forensx
    - PGADMIN_DEFAULT_PASSWORD=forensx
    ports:
      - "8080:80"
    depends_on: 
      - "postgres-server"

  flask-api:
    container_name: flask_api
    restart: always
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - "pgadmin"

  client:
    container_name: react_scisearch
    build:
      context: ./sci-search
      dockerfile: Dockerfile
    volumes:
      - "./sci-search:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - "flask-api"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:5000
